<?php

// matrix multiplication of all the answers

// need denomination variable to be generated by matrix results

// the y axis will be the selected answers

// the x axis will be each denomination

// this will work like a pugh matrix

//set the possible answers as values then use conditional statements to detect what answer they chose, then with that I will add +1 to each score and at the end get the highest variable integer and say that is the one that they are

// Define matrix of questions and answers
$matrix = [
  'q1' => [
    'a' => 1,
    'b' => 2,
    'c' => 3
  ],
  'q2' => [
    'a' => 3,
    'b' => 2,
    'c' => 1
  ],
  'q3' => [
    'a' => 2,
    'b' => 1,
    'c' => 3
  ],
  'q4' => [
    'a' => 1,
    'b' => 3,
    'c' => 2
  ]
];

// Get answers from form submission
$answers = $_POST;

// Calculate score for each answer
$scores = [];

foreach ($answers as $question => $answer) {
  if (isset($matrix[$question][$answer])) {
    if (!isset($scores[$answer])) {
      $scores[$answer] = 0;
    }
    $scores[$answer] += $matrix[$question][$answer];
  }
}

// Determine highest scoring answer
$highestScore = 0;
$highestAnswer = '';

foreach ($scores as $answer => $score) {
  if ($score > $highestScore) {
    $highestScore = $score;
    $highestAnswer = $answer;
  }
}

// Output highest scoring answer
echo "The highest scoring answer is $highestAnswer with a score of $highestScore";

?>